CREATE TABLE IF NOT EXISTS projects(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> '') ,
    priority INTEGER NOT NULL,
    description TEXT,
    deliverydate DATE NOT NULL
);


CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);


INSERT INTO projects(name, priority, description, deliverydate)
    VALUES('Make a Web app', 1, 'Using JS', '2022-05-11');

INSERT INTO projects(name, priority, description, deliverydate)
VALUES('Make a App', 1, 'Using Dart', '2022-01-01');

INSERT INTO projects(name, priority, description, deliverydate)
VALUES('Make a App IOS', 1, 'Using JAVA', '2022-88-01');

-- INSERT TASKS DATA

INSERT INTO tasks (name, done, projectId)
VALUES('Download Vuejs', false, 1);